name: Production Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SERTIS_BY_SSH }}

      - name: Connect to remote host and run commands
        run: |
          ssh -o StrictHostKeyChecking=no \
              -i ${{ secrets.SERTIS_BY_SSH }} \
              bitrix130@sertis.by \
              "cd /home/bitrix130/domains/sertis.by/public_html && git pull"
