name: Deployment Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/deploy_rsa
          chmod 600 ~/.ssh/deploy_rsa
      - name: Deploy to server
        run: |
          echo "Starting deployment..."
          ssh -i ~/.ssh/deploy_rsa -o StrictHostKeyChecking=no bitrix130@sertis.by "cd /home/bitrix130/domains/sertis.by/public_html && git pull"
          echo "Deployment completed."
