name: Command via SSH

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: running commands via OPEN SSH Private Key
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd '/home/bitrix130/public_html' && git pull
          host: sertis.by
          username: bitrix130
          privateKey: ${{ secrets.KEY }}
        env:
          CI: true
          
          
